### ISSUE TITLE
Instruction substitution help

### ISSUE THREAD

**Issue by deardeer7** [RyanWangGit/MIPS-CPU#28]
I encountered an operation to **print a string**, so I needed to use the **LA** instruction. The specific code is shown in the figure below. Is there any alternative solution?
![image](https://user-images.githubusercontent.com/42965045/116673001-69051100-a9d5-11eb-85b1-7d1c51f6d183.png)
And str1 is defined as `str1: .asciiz "Target is found at "`.
Thx in advance.

**Comment by deardeer7** [comment]
There are three **LA** instructions in my code. I tried replacing them with the **LW** instructions, but it didn't work.
Here is my complete code：
```asm
# Created by Deardeer on 2021/4/30
# bs.asm - a program for binary search

# C++ code
# int nums[] = {1,2,3,4,5,6,7};
# int target = 4;
# int l = 0, r = 6, m;
# while(l <= r) {
#     m = (l + r) / 2;
#     if(nums[m] == target) {
#         cout << "Target is found at " << ans;
#         return 0;
#     }
#     else if(nums[m] > target) r = m - 1;
#     else l = m + 1;
# }
# cout << "Target is not found";
# return 0;

.data # data declaration
    nums: .space 28
    target: .word 6
    str1: .asciiz "Target is found at "
    str2: .asciiz "Target is not found"
    
.text
main:
    # data init
    lw $t0, nums # put nums array's adress in $t0
    addi $t1, $zero 1 # current generated value
    sw $t1, 0($t0) # nums[0] = 1
    addi $t1, $t1, 1
    sw $t1, 4($t0) # nums[1] = 2
    addi $t1, $t1, 1
    sw $t1, 8($t0) # nums[3] = 3
    addi $t1, $t1, 1
    sw $t1, 12($t0) # nums[3] = 4
    addi $t1, $t1, 1
    sw $t1, 16($t0) # nums[4] = 5
    addi $t1, $t1, 1
    sw $t1, 20($t0) # nums[5] = 6
    addi $t1, $t1, 1
    sw $t1, 24($t0) # nums[6] = 7

    add $s0, $zero, $zero # l = 0
    addi $s1, $zero, 6 # r = 6
    la $t0, nums # put nums array's adress in $t0
    lw $t1, target # get target and store it in $t1

while:
    slt $t2, $s1, $s0 # $t2 = (r < l) ? 1 : 0
    bne $t2, $zero, not_found # judge l <= r

    # m = (l + r) / 2
    addu $t3, $s0, $s1
    srl $t3, $t3, 1 # (l + r) / 2
   
    sll $t4, $t3, 2 # m * 4
    addu $t4, $t4, $t0
    lw $t4, ($t4) # nums[m]

    # compare nums[m] with target
    bne $t4, $t1, not_equal
    add $a0, $t3, $zero # nums[m] = target, found target
    jal found

not_equal:
    slt $t5, $t4, $t1 # (nums[m] < target) ? 1 : 0
    bne $t5, $zero, right # nums[m] < target
    beq $t5, $zero, left # nums[m] > target

right:
    # l = m + 1
    addi $s0, $t3, 1
    b while

left:
    # r = m - 1
    addi $t5, $zero, 1
    sub $s0, $t3, $t5
    b while

not_found:
    # cout << "Target is not found";
    addi $v0, $zero, 4
    la $a0, str2
    syscall

    addi $v0, $zero, 10 # exit
    syscall

found: 
    add $t0, $a0, $zero
    addi $t0, $t0, 1

    # cout << "Target is found at ";
    addi $v0, $zero, 4
    la $a0, str1
    syscall

    # cout << m;
    addi $v0, $zero, 1
    add $a0, $t0, $zero
    syscall

    addi $v0, $zero, 10 # exit
    syscall
```

**Comment by yuxincs** [comment]
The problem is that I only used the hex screen component of logisim for data display, so the CPU only supports `syscall` where `$v0` is either 34 or 10 (for printing integers and halting, see [this](https://courses.missouristate.edu/kenvollmar/mars/help/syscallhelp.html)). 

If you'd like, you can try to add the support for displaying strings (I think there's full-fledged screen in logisim?). Basically you need to add support for `la` instruction and also add support for proper decoding in `Syscall Decoding` component in the cpu to generate proper signals to display strings on the full-fledged screen.

**Comment by yuxincs** [comment]
If supporting `la` is too laborious, a quick hack can be writing a loop to read each byte from the string, but again you still need make syscall decoder to support a more advanced screen.

**Comment by deardeer7** [comment]
All right, thanks a lot. I got that. Forget about printing strings on the screen, the other thing that I'm going to use for the `LA ` instruction is the array header address that I'm going to store so that I can get array element by offset. I tried to use the` LW ` instruction but got an error. Is there any solution to this?
Here are two screenshots about this.

![image](https://user-images.githubusercontent.com/42965045/116716563-7be60880-aa0a-11eb-82bd-bc01e3329204.png)
![image](https://user-images.githubusercontent.com/42965045/116716617-90c29c00-aa0a-11eb-87a4-0569ff1dd53f.png)

**Comment by deardeer7** [comment]
You can try it  on my code, and just comment out the print string part.

**Comment by yuxincs** [comment]
Yeah that's because there's no proper support of `la` instruction in the CPU since this is just a toy CPU I made for the computer architecture course project years ago. Using `lw` won't help since it's loading the value instead of loading the actual address.

As you can see, the benchmark uses memory address 0 as the starting address and manually put values in it. 

https://github.com/yxwangcs/MIPS-CPU/blob/8086ea7664523a7f2425e13581e3ca0670b2460c/Benchmarks/Benchmark.asm#L135-L148

A hack that you can do, if you really want to make it work, is just put the `nums` at the address 0, and manually init it like the benchmarks. Honestly it's just better to properly support `la`, but that may require some work, the book I referenced [1] should contain the details.

[1] Harris, David, and Sarah Harris. Digital design and computer architecture. Morgan Kaufmann, 2010.

**Comment by deardeer7** [comment]
Okay, thank you very much, I am ready to give it a try.

**Comment by deardeer7** [comment]
I have done as you said, and there is no problem with the code now. However, when I was using the pipeline circuit simulation on Logisim, I encountered a problem. **The LED display could not display** my calculation results correctly. 
The result is supposed to be 000006 and I have checked it on Mars.

![Mars result](https://user-images.githubusercontent.com/42965045/116805368-c4abd780-ab58-11eb-97a8-b195330b213e.png)

![wrong display](https://user-images.githubusercontent.com/42965045/116805042-2585e080-ab56-11eb-895a-d54744e335a7.png)

my code: 
```asm
# Created by Deardeer on 2021/5/2
# binary_search.asm - a program for binary search

# C++ code
# int nums[] = {1,2,3,4,5,6,7};
# int target = 6;
# int l = 0, r = 6, m;
# while(l <= r) {
#     m = (l + r) / 2;
#     if(nums[m] == target) {
#         cout << ans + 1; // index of target in nums (indexed from 1)
#         return 0;
#     }
#     else if(nums[m] > target) r = m - 1;
#     else l = m + 1;
# }
# cout << "-1";
# return 0;

.data
.text
main:
    # data init
    addi $s0,$0, 1           # current generated value
    addi $s1,$0,0            # nums array's address

    sw $s0,0($s1)            # nums[0] = 1
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[1] = 2
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[2] = 3
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[3] = 4
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[4] = 5
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[5] = 6
    addi $s0,$s0,1
    addi $s1,$s1,4
    sw $s0,0($s1)            # nums[6] = 7

    # search init
    add $s3, $zero, $zero    # l = 0
    addi $s4, $zero, 6       # r = 6
    addi $s1, $zero, 0       # s1 points to nums header address
    add $t1, $zero, 6        # target = 6
while:
    slt $t2, $s4, $s3        # (r < l) ? 1 : 0
    bne $t2, $zero, not_found# judge l <= r
    
    # m = (l + r) / 2
    addu $t2, $s3, $s4
    srl $t2, $t2, 1          # get m : sum / 2

    sll $s0, $t2, 2          # get offset: m * 4
    add $s0, $s0, $s1        # convert index to address
    lw $s0, ($s0)            # nums[m]

    # compare nums[m] with target
    bne $s0, $t1, not_equal
    jal found                # nums[m] = target, found target

not_equal:
    slt $t3, $s0, $t1        # (nums[m] < target) ? 1 : 0
    bne $t3, $zero, right    # nums[m] < target, find in right
    beq $t3, $zero, left     # nums[m] > target, find in left

right:
    # l = m + 1
    addi $s3, $t2, 1
    b while                  # continue finding

left:
    # r = m - 1
    addi $s4, $t2, -1
    b while                  # cotinue finding

not_found:
    addi $v0, $zero, 34      # print integer on LED display
    addi $a0, $zero, -1      # target not found, return -1
    syscall                  # display on the screen

    addi $v0, $zero, 10      # exit
    syscall

found:
    addi $v0, $zero, 34      # print integer on LED display
    addi $a0, $t2, 1         # target found, return m + 1
    syscall                  # display on the screen

    add $v0, $zero, 10       # exit
    syscall
```
Then I used another code to test the light display and the results were displayed correctly. I do not understand. 

![light display test](https://user-images.githubusercontent.com/42965045/116805238-9b3e7c00-ab57-11eb-9a2f-b45268968003.png)


another light display test code:
```asm
.data
.text
main:
    addi $v0, $zero, 34
    addi $a0, $zero, 1
    syscall
    addi $v0, $zero, 34
    addi $a0, $zero, 2
    syscall
    addi $v0, $zero, 34
    addi $a0, $zero, 3
    syscall
```

**Comment by yuxincs** [comment]
Looks like it hits the `not_found` block, displaying -1 (0xFFFFFFFF)

```assembly
not_found:
    addi $v0, $zero, 34      # print integer on LED display
    addi $a0, $zero, -1      # target not found, return -1
    syscall                  # display on the screen
```

It may be a bug in the CPU, does it work on single cycle cpu? if it succeeds in single cycle cpu, then the bug might be related to hazards. 

Logisim can run one tick at a time, and Mars shows the data for each register. I remember when I was debugging the CPU I would run the instruction one by one and check if the registers (`regfile` circuit) are in line with what Mars says, and see how instruction / data flows in the pipelines. 

I currently don't have the time to do this myself, if you're interested, you're welcome to test which particular instruction diverges from Mars simulator. I can provide some high-level description of what each component does.

**Comment by deardeer7** [comment]
I just tried it on single cycle cpu, but I get the same result “FFFFFFFF” as the pipeline CPU. I am going to try to single-step debug the CPU in Logisim. BTW, I have one more question, why is it that every time I export a HEX file from Mars, I can't use it directly in Logisim. When I choose to load image, Logisim tells me “Image file has invalid format header”. Then I compared my HEX file with yours and the first line "V2.0 RAW" was missing. I have to manually add the first line in my hex file such that I can use it in Logisim. And it does, I can load the image normally after adding. Was there a problem with my selection when exporting in Mars? 

selection in Mars when exporting:
![dump hex file option](https://user-images.githubusercontent.com/42965045/116836824-9c74b500-abfa-11eb-8b3d-ef66034cd6d3.png)

open error when load image in Logisim
![Open error](https://user-images.githubusercontent.com/42965045/116836817-8f57c600-abfa-11eb-8b1a-ee2a4c85f687.png)

**Comment by yuxincs** [comment]
I would say it's a requirement from logisim, and I honestly don't know the reason. I had to add that line to any file Mars generates, too. It's just a magic "number" that logisim expects to find at the start of assembly file..

**Comment by deardeer7** [comment]
And you're right about the wrong result "FFFFFFFF". I changed the "not_found"  return value to "1", then tried agagin in Logisim. I found that whatever the target value is, the result is always 1. I don't know if there is a bug in my code  or something.

![image](https://user-images.githubusercontent.com/42965045/116837479-32a9da80-abfd-11eb-94d9-3c919b4b1993.png)

**Comment by yuxincs** [comment]
Mars should the the authority here, if Mars runs fine the code probably should be fine. The reason could be that you're using instructions not supported by the CPU. A second glance through your generated assembly code shows that you're using `b` instruction (unconditional branch), which is not implemented (see [list of supported instructions here](https://github.com/yxwangcs/MIPS-CPU#supported-instructions)). You could try changing the `b` instructions to `j` (unconditional jump).

**Comment by deardeer7** [comment]
> Mars should the the authority here, if Mars runs fine the code probably should be fine. The reason could be that you're using instructions not supported by the CPU. A second glance through your generated assembly code shows that you're using `b` instruction (unconditional branch), which is not implemented (see [list of supported instructions here](https://github.com/yxwangcs/MIPS-CPU#supported-instructions)). You could try changing the `b` instructions to `j` (unconditional jump).
It works!!! It's my fault. I didn't notice that you didn't implement the B instruction. Thank you for spending so much time helping me!
![image](https://user-images.githubusercontent.com/42965045/116838029-7998cf80-abff-11eb-90aa-85b6686354bf.png)
