### ISSUE TITLE
ADDIU uses zero extension instead of signed extension on immediate value

### ISSUE THREAD

**Issue by Oxore** [RyanWangGit/MIPS-CPU#29]
I was recently tinkering with `mipsel-elf-gcc` to compile simple C program and run on a pipelined version of MIPS done by this beautiful implementation in Logisim. I was eager to figure out how MIPS instruction pipelining works in details.

I tried to write program that increments and decrements a value and it turns out that GCC uses `addiu` instruction for subtraction. So it looks like this from `objdump` output:

```
  18:   2402ffff        addiu   v0,zero,-1
```

It just uses `0xffff` in immediate field of ADDIU as -1!

Indeed, the [MIPS32 specification](https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00086-2B-MIPS32BIS-AFP-6.06.pdf) on page 36 explicitly mentions that for ADDIU instruction immediate value must be sign-extended (to match destination register bitness, i.e. 32, I guess):

```
temp <- GPR[rs] + sign_extend(immediate)
GPR[rt] <- temp
```

That should work as subtraction when the most significant bit of immediate value is 1, even though ADDIU misleadingly has the word "unsigned" in it's name, which may be a little bit misleading.

However in current implementation the part of the opcode decoder that makes zero extension happen instead of sign extension is this:

![IsUnsigned opcode decoding circuit](https://user-images.githubusercontent.com/17534278/177054120-32d06923-252d-4384-8e90-01a412c6c5c9.png)

001001... It is literally just ADDIU! And it indicates `IsUnsigned` flag that is wrong and misleading, I think.

Actualy there is only 3 instructions in the specification that use zero extension at all - ANDI, ORI, and XORI. All other instructions, that work with immediate values or directly specified offsets, use signed extension.

With that said I suppose the following fix. It addresses all three zero extending instructions:

```
ANDI 001100
ORI  001101
XORI 001110
```

Which reduces to expression like this: `ZeroExtend = 00110x || 001110`

The fixed opcode decoding circuit:

![Zero extension related circuit fix](https://user-images.githubusercontent.com/17534278/177054621-f0e9f108-19a3-4046-bd8a-deb044bcae0d.png)

I've made the fix for all three implementations and it at least doesn't brake preloaded test program. You can look at it in the repo I forked, in [zero_extend](https://github.com/Oxore/MIPS-CPU/tree/zero_extend) branch (commit permalnk: https://github.com/Oxore/MIPS-CPU/commit/e2bbd2d8d2afa0a06dd19d878dfdfa10bb72adf7, [browse](https://github.com/Oxore/MIPS-CPU/tree/e2bbd2d8d2afa0a06dd19d878dfdfa10bb72adf7)). If it's OK, I can file a merge request from this branch.

**Comment by yuxincs** [comment]
Thanks for the issue! I'm glad you are interested in this project. I had great fun developing this a long time ago.

I took a look into this issue, and it appears that I really was confused by the name "ADDIU". Actually, even the [specs](https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/[MD00086-2B-MIPS32BIS-AFP-6.06.pdf](https://s3-eu-west-1.amazonaws.com/downloads-mips/documents/MD00086-2B-MIPS32BIS-AFP-6.06.pdf)) admits the confusing name:
> The term “unsigned” in the instruction name is a misnomer;

Your solutions look great to me, and please send a PR! It would be even better if you could include a test for `ADDIU` in the benchmark file. You can be creative about how the tests would look like, you just need to use a `syscall` to display something on the LED screen for verification. For example, displaying the value of  $s3 would be:

```
add    $a0,$0,$s3       # display $s3
addi   $v0,$0,34         # system call for LED display 
syscall                 # display 
```

You can compile the assembly code using [Mars](http://courses.missouristate.edu/kenvollmar/mars/), be sure to compile using Compact memory layout with address starting at 0.

That said, I'm more than happy to merge your PR even without tests! I can try to find some time to add them later myself 😃
